### PR TITLE
Responsive left and right sidebar

### PR DESCRIPTION
**Pull request by kkostepski**
Regarding #6, sidebars are now responsive and we can see everything on smaller laptop screens. If the sidebars are too small, the scrollbar appears.

### CODE REVIEW

**Comment by konradkalemba** [comment]
Works great! One problem I found that the button can be hovered by the bottom buttons.

Thanks for help! 👍 
image

**Comment by kkostepski** [comment]
1. Sorry for commits after I raised PR, but my IDE autoformatted my code and I didn't notice that.
2. If you mean bottom buttons overlapping button "więcej informacji", that was not PR scope, but I can look at this as well :)

**Comment by konradkalemba** [comment]
@kkostepski 
1. No problem. :)
2. Yes, that would be great.

**Comment by kkostepski** [comment]
OK, I have pushed changes. Overlapping buttons should be fixed.

**Pull request merged**
