### PR TITLE
Fix Contributors component

### PR DESCRIPTION
**Pull request by mhajder**

### CODE REVIEW

**Comment by konradkalemba** [comment]
@mhajder Does it prevent the error you mentioned in #15?

**Comment by mhajder** [comment]
> @mhajder Does it prevent the error you mentioned in #15?

Yes.
You could still add a conditional statement that doesn't display these elements:
https://github.com/konradkalemba/korona.ws/blob/647a891ef2dc7963b0a6b3b6cbac9d929e765f24/src/components/Layout/Desktop.jsx#L114-L115

Also after rewriting the layout, the #12 Pull Request did not work.

**Comment by konradkalemba** [comment]
@mhajder Hmm, you're right. But in [your's pull request preview deployment](https://korona-ws-git-fork-mhajder-fix-contributorscomponent.konradkalemba.now.sh/) custom scrollbars work, at least for me.

**Comment by konradkalemba** [comment]
Ahh, it was before the layout changes were implemented. Never mind.

**Pull request merged**
