### PR TITLE
Feature/44 daily cases

### PR DESCRIPTION
**Pull request by Kamil-kozlowski**

### CODE REVIEW

**Comment by konradkalemba** [comment]
Great! 👍 
What do you think about adding deaths and cures next to cases bar?

**Comment by Kamil-kozlowski** [comment]
> Great! 👍
> What do you think about adding deaths and cures next to cases bar?

@konradkalemba Not sure if there is enough space to put two additional bars next to cases bar so the chart remains clear to understand. I can try to use [StackedBarChart](http://recharts.org/en-US/examples/StackedBarChart) to place deaths and cures on top of cases and see how it looks.

**Comment by konradkalemba** [comment]
@Kamil-kozlowski You're right, let's try with stacked bar.

**Comment by Kamil-kozlowski** [comment]
@konradkalemba I changed to stacked bar chart - looks good in my opinion.
I mocked some data to see how it looks for greater data diversity. 
image

**Comment by konradkalemba** [comment]
@Kamil-kozlowski Looks great!

One more thing I noticed: tabs' titles are in two lines - how about changing them to 'Wszystkie' and 'Dziennie' accordingly? Or maybe `Wykres` and `Histogram`? I can't think of some good names.

**Comment by Kamil-kozlowski** [comment]
@konradkalemba I changed it to `Wszystkie/Overall` and `Dzienne/Daily` - in my opinion the simpler we keep them the better. I'm not quite sure if `Histogram` is a commonly understandable word.
Also, I've extracted ResponsiveTab component and put it in place of other Tab components inside the app. Now their look and positioning is unified. Please take a look at that when reviewing changes.

**Pull request merged**
