### PR TITLE
Refactor DataElement component

### PR DESCRIPTION
**Pull request by nowNick**
Hi!

First of all: Great job guys! 👏 

I was planning on adding some charts to the historical data but first I wanted to understand how things work and I noticed I could add a few optimizations to DataElement component. I extracted common elements and made sure `prepareData` is called only when cases or deaths changes. 

I know it's not a lot but I wanted to start here so that things might be a bit easier in the future.

Please let me know what you think 🙃 

---
PS: Would you consider adding `prettier` ? I'm not sure if I followed your style guide and I think adding it may help future contributors 🤔

### CODE REVIEW

**Comment by konradkalemba** [comment]
Hi, thanks for kind words and your pull request!

I agree, there are components that need refactoring and `DataElement` is definitely one of them. I will review the changes tonight, but it looks good at the first glance. 👍 

Regarding `prettier` - yes, absolutely, I will try to configure it tonight as well.

**Comment by konradkalemba** [comment]
I noticed the problem with the latest cases order, but I don't know why it is like that.

**Comment by nowNick** [comment]
@konradkalemba oh good catch! I just pushed a fix.

I accidentally removed `slice` and `reversed` when refactoring.

**Comment by konradkalemba** [comment]
Looks good! :) Thanks for your contribution.

**Comment by mhajder** [comment]
These changes probably ruined "Informacje". There is an error after clicking.

**Comment by konradkalemba** [comment]
@mhajder I don't see any problem. Where did you encounter that problem? This pull request hasn't been deployed to production yet.

**Comment by mhajder** [comment]
However, it's API's fault.
When API rate limit exceeded for GitHub, you cannot open the information page.

**Comment by konradkalemba** [comment]
@mhajder Oh, I see. I thought `collaborators` endpoint in GitHub's API is public and therefore doesn't have limitations. I'll add an API key and we'll see how it goes. Thanks for the info!

**Comment by mhajder** [comment]
@konradkalemba 
I don't know if it's a good idea to add the API key to GH publicly. But you could do a conditional error-catching function here. I will try to do this.
https://github.com/konradkalemba/korona.ws/blob/4a991d3cf053d72d879d7e66c35290df1d39e6d3/src/components/Contributors/Contributors.jsx#L10-L13

**Comment by konradkalemba** [comment]
@mhajder I didn't plan to do so - I wanted to store it as an environment variable. But now thinking about it, my token still would be exposed as it would be inserted into the code during build process. Thanks for the heads-up. 

Catching error will definitely solve the problem with popup not showing. 👍

**Pull request merged**
